/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MySpringCoreDemo2;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;

import com.cg.mybeans.Employee;

public class Library {
   public static void main(String[] args) {
	//BeanFactory beanFactory = new XmlBeanFactory(new ClassPathResource("mybean.xml"));
	//beanFactory.getBean("employee1",Employee.class );
	// Employee em = beanFactory.getBean("employee1",Employee.class );
	  // ApplicationContext actxt = new ClassPathXmlApplicationContext("mybean.xml"); // auto created object using this and its is preferred way
	   ApplicationContext actxt = new AnnotationConfigApplicationContext("com.cg.mybeans","com.cg.config");
	  //Employee em = actxt.getBean("employee1",Employee.class );
	 // em.details();
	
}
}
